import GraphCertificate
import Mathlib

/- Generated concrete semantic dependency certificate.
The reconstructed accepted proof below supplies the proof pieces;
the final command kernel-checks and compares every selected edge. -/
-- graph_id: p1552_index_two_infinite_cyclic_classification
-- certificate_kind: embedded_theorem_replay
-- topology_sha256: b970c05a80a45b5cb42281387b00efc48d0120f20aec20b1b700ceda483f090b
-- reconstructed_proof_sha256: ca16ec0b4eb68fc59e6e018796ea3e9ad62d3dfff9476d84e70f557d46735815
-- selected_edge_count: 4

/- accepted add_to_file helper 1 -/

open Subgroup

/-- Two-sided normal forms for a group generated by an involution and a conjugated generator. -/
def twoSidedNF {G : Type*} [Group G] (a b : G) : Set G :=
  {x | ∃ c : Bool, ∃ k : ℤ, x = if c then a * b ^ k else b ^ k}

lemma one_mem_twoSidedNF {G : Type*} [Group G] (a b : G) :
    (1 : G) ∈ twoSidedNF a b := by
  refine ⟨false, 0, ?_⟩
  simp

lemma generator_left_mem_twoSidedNF {G : Type*} [Group G] (a b : G) :
    a ∈ twoSidedNF a b := by
  refine ⟨true, 0, ?_⟩
  simp

lemma generator_right_mem_twoSidedNF {G : Type*} [Group G] (a b : G) :
    b ∈ twoSidedNF a b := by
  refine ⟨false, 1, ?_⟩
  simp

lemma zpow_conjugate_eq_neg {G : Type*} [Group G] {a b : G}
    (hconj : a * b * a⁻¹ = b⁻¹) (k : ℤ) :
    a * b ^ k = b ^ (-k) * a := by
  have h : (a * b * a⁻¹) ^ k = (b⁻¹) ^ k := congrArg (fun x => x ^ k) hconj
  rw [conj_zpow] at h
  calc
    a * b ^ k = (a * b ^ k * a⁻¹) * a := by group
    _ = (b⁻¹) ^ k * a := by rw [h]
    _ = b ^ (-k) * a := by rw [inv_zpow']

lemma zpow_mul_eq_left {G : Type*} [Group G] {a b : G}
    (hconj : a * b * a⁻¹ = b⁻¹) (k : ℤ) :
    b ^ k * a = a * b ^ (-k) := by
  simpa using (zpow_conjugate_eq_neg hconj (-k)).symm

/- accepted add_to_file helper 2 -/
lemma twoSidedNF_mul_of_inversion {G : Type*} [Group G] {a b : G}
    (hconj : a * b * a⁻¹ = b⁻¹) (hsq : a * a = 1)
    {x y : G} (hx : x ∈ twoSidedNF a b) (hy : y ∈ twoSidedNF a b) :
    x * y ∈ twoSidedNF a b := by
  rcases hx with ⟨cx, k, rfl⟩
  rcases hy with ⟨cy, l, rfl⟩
  cases cx <;> cases cy
  · refine ⟨false, k + l, ?_⟩
    simp [zpow_add]
  · refine ⟨true, l - k, ?_⟩
    simp
    calc
      b ^ k * (a * b ^ l) = (b ^ k * a) * b ^ l := by group
      _ = (a * b ^ (-k)) * b ^ l := by rw [zpow_mul_eq_left hconj]
      _ = a * b ^ (l - k) := by
        rw [mul_assoc, ← zpow_add]
        ring_nf
  · refine ⟨true, k + l, ?_⟩
    simp
    rw [mul_assoc, ← zpow_add]
  · refine ⟨false, l - k, ?_⟩
    simp
    calc
      (a * b ^ k) * (a * b ^ l) = ((a * b ^ k) * a) * b ^ l := by group
      _ = ((b ^ (-k) * a) * a) * b ^ l := by rw [zpow_conjugate_eq_neg hconj]
      _ = (b ^ (-k) * (a * a)) * b ^ l := by group
      _ = b ^ (l - k) := by
        rw [hsq, mul_one, ← zpow_add]
        ring_nf

lemma twoSidedNF_inv_of_inversion {G : Type*} [Group G] {a b : G}
    (hconj : a * b * a⁻¹ = b⁻¹) (hsq : a * a = 1)
    {x : G} (hx : x ∈ twoSidedNF a b) :
    x⁻¹ ∈ twoSidedNF a b := by
  rcases hx with ⟨c, k, rfl⟩
  cases c
  · refine ⟨false, -k, ?_⟩
    simp [zpow_neg]
  · have hainv : a⁻¹ = a := by
      apply inv_eq_of_mul_eq_one_left hsq
    refine ⟨true, k, ?_⟩
    simp only [↓reduceIte]
    calc
      (a * b ^ k)⁻¹ = b ^ (-k) * a := by
        rw [mul_inv_rev, hainv, zpow_neg]
      _ = a * b ^ k := by
        rw [zpow_mul_eq_left hconj (-k), neg_neg]

/- accepted add_to_file helper 3 -/
lemma twoSidedNF_eq_univ_of_inversion {G : Type*} [Group G] (a b : G)
    (hconj : a * b * a⁻¹ = b⁻¹) (hsq : a * a = 1)
    (hgen : Subgroup.closure {a, b} = ⊤) :
    twoSidedNF a b = Set.univ := by
  apply Set.eq_univ_iff_forall.mpr
  intro x
  have hx : x ∈ Subgroup.closure {a, b} := by simp [hgen]
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
      simp at hy
      rcases hy with rfl | rfl
      · exact generator_left_mem_twoSidedNF y b
      · exact generator_right_mem_twoSidedNF a y
  | one => exact one_mem_twoSidedNF a b
  | mul y z hy hz ihy ihz =>
      exact twoSidedNF_mul_of_inversion hconj hsq ihy ihz
  | inv y hy ihy =>
      exact twoSidedNF_inv_of_inversion hconj hsq ihy

/- accepted add_to_file helper 4 -/
lemma zpow_commute_left {G : Type*} [Group G] {a b : G}
    (hcomm : a * b = b * a) (k : ℤ) :
    b ^ k * a = a * b ^ k :=
  (Commute.zpow_right hcomm k).symm.eq

/- accepted add_to_file helper 5 -/
lemma twoSidedNF_mul_of_commute_square {G : Type*} [Group G] {a b : G}
    (hcomm : a * b = b * a) {n : ℤ} (hsq : a * a = b ^ (2 * n))
    {x y : G} (hx : x ∈ twoSidedNF a b) (hy : y ∈ twoSidedNF a b) :
    x * y ∈ twoSidedNF a b := by
  rcases hx with ⟨cx, k, rfl⟩
  rcases hy with ⟨cy, l, rfl⟩
  cases cx <;> cases cy
  · refine ⟨false, k + l, ?_⟩
    simp [zpow_add]
  · refine ⟨true, k + l, ?_⟩
    simp
    calc
      b ^ k * (a * b ^ l) = (b ^ k * a) * b ^ l := by group
      _ = (a * b ^ k) * b ^ l := by rw [zpow_commute_left hcomm]
      _ = a * b ^ (k + l) := by
        rw [mul_assoc, ← zpow_add]
  · refine ⟨true, k + l, ?_⟩
    simp
    rw [mul_assoc, ← zpow_add]
  · refine ⟨false, 2 * n + k + l, ?_⟩
    simp
    calc
      (a * b ^ k) * (a * b ^ l) = (a * (b ^ k * a)) * b ^ l := by group
      _ = (a * (a * b ^ k)) * b ^ l := by rw [zpow_commute_left hcomm]
      _ = ((a * a) * b ^ k) * b ^ l := by group
      _ = b ^ (2 * n + k + l) := by
        rw [hsq, ← zpow_add, ← zpow_add]

/- accepted add_to_file helper 6 -/
lemma twoSidedNF_inv_of_commute_square {G : Type*} [Group G] {a b : G}
    (hcomm : a * b = b * a) {n : ℤ} (hsq : a * a = b ^ (2 * n))
    {x : G} (hx : x ∈ twoSidedNF a b) :
    x⁻¹ ∈ twoSidedNF a b := by
  rcases hx with ⟨c, k, rfl⟩
  cases c
  · refine ⟨false, -k, ?_⟩
    simp [zpow_neg]
  · refine ⟨true, -k - 2 * n, ?_⟩
    simp only [↓reduceIte]
    apply inv_eq_of_mul_eq_one_left
    calc
      (a * b ^ (-k - 2 * n)) * (a * b ^ k)
          = (a * (b ^ (-k - 2 * n) * a)) * b ^ k := by group
      _ = (a * (a * b ^ (-k - 2 * n))) * b ^ k := by
        rw [zpow_commute_left hcomm]
      _ = ((a * a) * b ^ (-k - 2 * n)) * b ^ k := by group
      _ = 1 := by
        rw [hsq, ← zpow_add, ← zpow_add]
        have hzero : 2 * n + (-k - 2 * n) + k = 0 := by ring
        rw [hzero]
        simp

lemma twoSidedNF_eq_univ_of_commute_square {G : Type*} [Group G] (a b : G)
    (hcomm : a * b = b * a) {n : ℤ} (hsq : a * a = b ^ (2 * n))
    (hgen : Subgroup.closure {a, b} = ⊤) :
    twoSidedNF a b = Set.univ := by
  apply Set.eq_univ_iff_forall.mpr
  intro x
  have hx : x ∈ Subgroup.closure {a, b} := by simp [hgen]
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
      simp at hy
      rcases hy with rfl | rfl
      · exact generator_left_mem_twoSidedNF y b
      · exact generator_right_mem_twoSidedNF a y
  | one => exact one_mem_twoSidedNF a b
  | mul y z hy hz ihy ihz =>
      exact twoSidedNF_mul_of_commute_square hcomm hsq ihy ihz
  | inv y hy ihy =>
      exact twoSidedNF_inv_of_commute_square hcomm hsq ihy

/- accepted add_to_file helper 7 -/
noncomputable def mulEquivOfTwoSidedNF {P K : Type*} [Group P] [Group K]
    (f : P →* K) (a b : P) (v t : K)
    (fa : f a = v) (fb : f b = t)
    (hnf : twoSidedNF a b = Set.univ)
    (hgenK : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    P ≃* K := by
  have hsubset : ({v, t} : Set K) ⊆ f.range := by
    intro x hx
    simp at hx
    rcases hx with rfl | rfl
    · exact ⟨a, fa⟩
    · exact ⟨b, fb⟩
  have hle : Subgroup.closure {v, t} ≤ f.range := (Subgroup.closure_le _).mpr hsubset
  have hrange : f.range = ⊤ := by
    apply top_unique
    rwa [hgenK] at hle
  have hsurj : Function.Surjective f := MonoidHom.range_eq_top.mp hrange
  have hker : f.ker = ⊥ := by
    rw [Subgroup.eq_bot_iff_forall]
    intro p hp
    rw [MonoidHom.mem_ker] at hp
    have hpnf : p ∈ twoSidedNF a b := by
      rw [hnf]
      trivial
    rcases hpnf with ⟨c, k, rfl⟩
    cases c
    · have ht : t ^ k = 1 := by
        simpa [fb] using hp
      have hk : k = 0 := by
        apply htinj
        simpa using ht
      simp [hk]
    · have hvt : v * t ^ k = 1 := by
        simpa [fa, fb] using hp
      have hv_eq : v = t ^ (-k) := by
        calc
          v = (v * t ^ k) * (t ^ k)⁻¹ := by group
          _ = (t ^ k)⁻¹ := by rw [hvt, one_mul]
          _ = t ^ (-k) := by rw [zpow_neg]
      have hvmem : v ∈ Subgroup.zpowers t := by
        rw [Subgroup.mem_zpowers_iff]
        exact ⟨-k, hv_eq.symm⟩
      exact False.elim (hvH hvmem)
  have hinj : Function.Injective f := (MonoidHom.ker_eq_bot_iff f).mp hker
  exact MulEquiv.ofBijective f ⟨hinj, hsurj⟩

/- accepted add_to_file helper 8 -/
def classificationCommRels (n : ℤ) : Set (FreeGroup (Fin 2)) :=
  {FreeGroup.of (0 : Fin 2) * FreeGroup.of (1 : Fin 2) *
      (FreeGroup.of (0 : Fin 2))⁻¹ * (FreeGroup.of (1 : Fin 2))⁻¹,
    (FreeGroup.of (0 : Fin 2)) ^ (2 : ℕ) *
      ((FreeGroup.of (1 : Fin 2)) ^ (2 * n))⁻¹}

def classificationInvRels : Set (FreeGroup (Fin 2)) :=
  {FreeGroup.of (0 : Fin 2) * FreeGroup.of (1 : Fin 2) *
      (FreeGroup.of (0 : Fin 2))⁻¹ * FreeGroup.of (1 : Fin 2),
    (FreeGroup.of (0 : Fin 2)) ^ (2 : ℕ)}

/- accepted add_to_file helper 9 -/
lemma mem_zpowers_coe_generator {G : Type*} [Group G] (u : G)
    (y : Subgroup.zpowers u) :
    y ∈ Subgroup.zpowers (⟨u, Subgroup.mem_zpowers u⟩ : Subgroup.zpowers u) := by
  rcases y with ⟨x, hx⟩
  rw [Subgroup.mem_zpowers_iff] at hx ⊢
  rcases hx with ⟨q, rfl⟩
  refine ⟨q, ?_⟩
  ext
  simp

noncomputable def zmodTwoEquivZpowers {G : Type*} [Group G] (u : G)
    (hu : orderOf u = 2) :
    Multiplicative (ZMod 2) ≃* Subgroup.zpowers u := by
  refine zmodMulEquivOfGenerator (g := ⟨u, Subgroup.mem_zpowers u⟩) ?_ ?_
  · intro y
    exact mem_zpowers_coe_generator u y
  · rw [Nat.card_zpowers]
    change orderOf u = 2
    exact hu

/- accepted add_to_file helper 10 -/
noncomputable def zmodTwoHomOfOrderTwo {G : Type*} [Group G] (u : G)
    (hu : orderOf u = 2) : Multiplicative (ZMod 2) →* G :=
  (Subgroup.zpowers u).subtype.comp (zmodTwoEquivZpowers u hu).toMonoidHom

lemma zmodTwoHomOfOrderTwo_apply_one {G : Type*} [Group G] (u : G)
    (hu : orderOf u = 2) :
    zmodTwoHomOfOrderTwo u hu (Multiplicative.ofAdd (1 : ZMod 2)) = u := by
  simp [zmodTwoHomOfOrderTwo, zmodTwoEquivZpowers]

/- accepted add_to_file helper 11 -/
lemma mem_zpowers_multiplicative_int_one (z : Multiplicative ℤ) :
    z ∈ Subgroup.zpowers (Multiplicative.ofAdd (1 : ℤ)) := by
  rw [Subgroup.mem_zpowers_iff]
  refine ⟨Multiplicative.toAdd z, ?_⟩
  apply Multiplicative.toAdd.injective
  rw [Int.toAdd_zpow]
  simp

lemma mem_zpowers_multiplicative_zmod_two_one (c : Multiplicative (ZMod 2)) :
    c ∈ Subgroup.zpowers (Multiplicative.ofAdd (1 : ZMod 2)) := by
  rw [Subgroup.mem_zpowers_iff]
  fin_cases c
  · exact ⟨0, rfl⟩
  · exact ⟨1, rfl⟩

lemma closure_pair_product_int_zmod_two :
    Subgroup.closure
      ({(1, Multiplicative.ofAdd (1 : ZMod 2)),
        (Multiplicative.ofAdd (1 : ℤ), 1)} :
        Set (Multiplicative ℤ × Multiplicative (ZMod 2))) = ⊤ := by
  rw [Subgroup.eq_top_iff']
  intro x
  rcases x with ⟨z, c⟩
  have hz := mem_zpowers_multiplicative_int_one z
  have hc := mem_zpowers_multiplicative_zmod_two_one c
  rw [Subgroup.mem_zpowers_iff] at hz hc
  rcases hz with ⟨q, hq⟩
  rcases hc with ⟨w, hw⟩
  rw [← hq, ← hw]
  let a : Multiplicative ℤ × Multiplicative (ZMod 2) :=
    (1, Multiplicative.ofAdd (1 : ZMod 2))
  let b : Multiplicative ℤ × Multiplicative (ZMod 2) :=
    (Multiplicative.ofAdd (1 : ℤ), 1)
  have hprod : ((Multiplicative.ofAdd (1 : ℤ)) ^ q,
      (Multiplicative.ofAdd (1 : ZMod 2)) ^ w) = b ^ q * a ^ w := by
    ext <;> simp [a, b]
  rw [hprod]
  exact mul_mem
    (zpow_mem (Subgroup.subset_closure (by simp [a, b])) q)
    (zpow_mem (Subgroup.subset_closure (by simp [a, b])) w)

/- accepted add_to_file helper 12 -/
lemma not_isOfFinOrder_of_infinite_zpowers {G : Type*} [Group G] {t : G}
    (htinf : Infinite (Subgroup.zpowers t)) : ¬IsOfFinOrder t := by
  intro ht
  haveI : Infinite (Subgroup.zpowers t) := htinf
  haveI : Finite (Subgroup.zpowers t) := ht.finite_zpowers.to_subtype
  exact not_finite (Subgroup.zpowers t)

lemma zpow_injective_of_infinite_zpowers {G : Type*} [Group G] {t : G}
    (htinf : Infinite (Subgroup.zpowers t)) :
    Function.Injective fun k : ℤ => t ^ k :=
  injective_zpow_iff_not_isOfFinOrder.mpr
    (not_isOfFinOrder_of_infinite_zpowers htinf)

lemma not_mem_zpowers_of_closure_eq_top_index_two {G : Type*} [Group G] {v t : G}
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hindex : (Subgroup.zpowers t).index = 2) :
    v ∉ Subgroup.zpowers t := by
  intro hv
  have hsubset : ({v, t} : Set G) ⊆ Subgroup.zpowers t := by
    intro x hx
    simp at hx
    rcases hx with rfl | rfl
    · exact hv
    · exact Subgroup.mem_zpowers x
  have hle : Subgroup.closure {v, t} ≤ Subgroup.zpowers t :=
    (Subgroup.closure_le _).mpr hsubset
  have htop : (⊤ : Subgroup G) ≤ Subgroup.zpowers t := by
    rwa [hgen] at hle
  have h_eq : Subgroup.zpowers t = ⊤ := top_unique htop
  have hindex1 : (Subgroup.zpowers t).index = 1 :=
    Subgroup.index_eq_one.mpr h_eq
  omega

/- accepted add_to_file helper 13 -/
lemma sq_mem_zpowers_of_index_two {G : Type*} [Group G] {v t : G}
    (hindex : (Subgroup.zpowers t).index = 2) :
    v * v ∈ Subgroup.zpowers t := by
  haveI : (Subgroup.zpowers t).Normal :=
    Subgroup.normal_of_index_eq_two hindex
  let H := Subgroup.zpowers t
  have hcard : Nat.card (G ⧸ H) = 2 := by
    rw [← Subgroup.index_eq_card, hindex]
  have hq : ((QuotientGroup.mk' H) v) ^ 2 = 1 := by
    have h := pow_card_eq_one' (x := (QuotientGroup.mk' H) v)
    rwa [hcard] at h
  have hq2 : (QuotientGroup.mk' H) (v ^ (2 : ℕ)) = 1 := by
    simpa using hq
  have hmem : v ^ (2 : ℕ) ∈ H := (QuotientGroup.eq_one_iff _).mp hq2
  simpa [sq] using hmem

/- accepted add_to_file helper 14 -/
lemma conjugation_cases_of_index_two {G : Type*} [Group G] {v t : G}
    (hindex : (Subgroup.zpowers t).index = 2)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    v * t = t * v ∨ v * t * v⁻¹ = t⁻¹ := by
  haveI hnormal : (Subgroup.zpowers t).Normal :=
    Subgroup.normal_of_index_eq_two hindex
  have hmem1 : v * t * v⁻¹ ∈ Subgroup.zpowers t :=
    hnormal.conj_mem t (Subgroup.mem_zpowers t) v
  rw [Subgroup.mem_zpowers_iff] at hmem1
  rcases hmem1 with ⟨m, hm⟩
  have hconj : v * t * v⁻¹ = t ^ m := hm.symm
  have hmem2 : v⁻¹ * t * v ∈ Subgroup.zpowers t :=
    hnormal.conj_mem' t (Subgroup.mem_zpowers t) v
  rw [Subgroup.mem_zpowers_iff] at hmem2
  rcases hmem2 with ⟨l, hl⟩
  have hconji : v⁻¹ * t * v = t ^ l := hl.symm
  have hcycle : t = t ^ (l * m) := by
    calc
      t = v⁻¹ * (v * t * v⁻¹) * v := by group
      _ = v⁻¹ * t ^ m * v := by rw [hconj]
      _ = (v⁻¹ * t * v) ^ m := by
        have hz := (conj_zpow (a := v⁻¹) (b := t) (i := m)).symm
        simpa using hz
      _ = (t ^ l) ^ m := by rw [hconji]
      _ = t ^ (l * m) := (zpow_mul t l m).symm
  have hlm : l * m = 1 := by
    apply htinj
    calc
      t ^ (l * m) = t := hcycle.symm
      _ = t ^ (1 : ℤ) := by simp
  have hm_cases : m = 1 ∨ m = -1 := by
    rcases Int.eq_one_or_neg_one_of_mul_eq_one hlm with hl1 | hlneg1
    · left
      simpa [hl1] using hlm
    · right
      have hnegm : -m = 1 := by
        simpa [hlneg1] using hlm
      omega
  rcases hm_cases with hm1 | hmneg1
  · left
    have hconj1 : v * t * v⁻¹ = t := by simpa [hm1] using hconj
    calc
      v * t = (v * t * v⁻¹) * v := by group
      _ = t * v := by rw [hconj1]
  · right
    simpa [hmneg1] using hconj

/- accepted add_to_file helper 15 -/
lemma no_torsion_of_commute_square_odd {K : Type*} [Group K] {v t : K} {s : ℤ}
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hcomm : v * t = t * v)
    (hv2 : v * v = t ^ (2 * s + 1))
    (htinj : Function.Injective fun k : ℤ => t ^ k)
    (htors : ∃ x : K, x ≠ 1 ∧ IsOfFinOrder x) : False := by
  let w : K := v * t ^ (-s)
  have hw2 : w * w = t := by
    dsimp [w]
    calc
      (v * t ^ (-s)) * (v * t ^ (-s))
          = (v * (t ^ (-s) * v)) * t ^ (-s) := by group
      _ = (v * (v * t ^ (-s))) * t ^ (-s) := by
        rw [zpow_commute_left hcomm]
      _ = ((v * v) * t ^ (-s)) * t ^ (-s) := by group
      _ = t := by
        rw [hv2, ← zpow_add, ← zpow_add]
        have hone : 2 * s + 1 + -s + -s = 1 := by ring
        rw [hone]
        simp
  have ht_mem : t ∈ Subgroup.zpowers w := by
    rw [Subgroup.mem_zpowers_iff]
    refine ⟨2, ?_⟩
    rw [← hw2, zpow_ofNat, pow_two]
  have hv_mem : v ∈ Subgroup.zpowers w := by
    rw [Subgroup.mem_zpowers_iff]
    refine ⟨1 + 2 * s, ?_⟩
    calc
      w ^ (1 + 2 * s) = w * w ^ (2 * s) := by rw [zpow_add]; simp
      _ = w * (w * w) ^ s := by
        rw [zpow_mul w 2 s, zpow_ofNat, pow_two]
      _ = w * t ^ s := by rw [hw2]
      _ = v := by
        dsimp [w]
        calc
          (v * t ^ (-s)) * t ^ s = v * (t ^ (-s) * t ^ s) := by group
          _ = v := by rw [← zpow_add]; simp
  have hsubset : ({v, t} : Set K) ⊆ Subgroup.zpowers w := by
    intro x hx
    simp at hx
    rcases hx with rfl | rfl
    · exact hv_mem
    · exact ht_mem
  have hle : Subgroup.closure {v, t} ≤ Subgroup.zpowers w :=
    (Subgroup.closure_le _).mpr hsubset
  have hall : ∀ x : K, x ∈ Subgroup.zpowers w := by
    intro x
    have htop : (⊤ : Subgroup K) ≤ Subgroup.zpowers w := by
      rwa [hgen] at hle
    exact htop trivial
  rcases htors with ⟨x, hxne, hxfin⟩
  have hxmem := hall x
  rw [Subgroup.mem_zpowers_iff] at hxmem
  rcases hxmem with ⟨q, hq⟩
  have hx2 : x * x = t ^ q := by
    calc
      x * x = w ^ q * w ^ q := by rw [hq]
      _ = w ^ (q + q) := by rw [← zpow_add]
      _ = w ^ (2 * q) := by ring_nf
      _ = (w * w) ^ q := by
        rw [zpow_mul w 2 q, zpow_ofNat, pow_two]
      _ = t ^ q := by rw [hw2]
  have htqfin : IsOfFinOrder (t ^ q) := by
    rw [← hx2, ← pow_two x]
    exact hxfin.pow
  rcases isOfFinOrder_iff_pow_eq_one.mp htqfin with ⟨N, hNpos, hN⟩
  have hpow : t ^ (q * (N : ℤ)) = 1 := by
    calc
      t ^ (q * (N : ℤ)) = (t ^ q) ^ (N : ℤ) := zpow_mul t q N
      _ = 1 := by simpa using hN
  have hqN : q * (N : ℤ) = 0 := by
    apply htinj
    simpa using hpow
  have hNne : (N : ℤ) ≠ 0 := by omega
  have hq0 : q = 0 := by
    rcases mul_eq_zero.mp hqN with hq0 | hN0
    · exact hq0
    · exact False.elim (hNne hN0)
  apply hxne
  rw [← hq, hq0]
  simp

/- accepted add_to_file helper 16 -/
lemma square_exponent_even_of_torsion {K : Type*} [Group K] {v t : K} {r : ℤ}
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hcomm : v * t = t * v)
    (hv2 : v * v = t ^ r)
    (htinj : Function.Injective fun k : ℤ => t ^ k)
    (htors : ∃ x : K, x ≠ 1 ∧ IsOfFinOrder x) :
    Even r := by
  by_contra hnot
  have hodd : Odd r := Int.not_even_iff_odd.mp hnot
  rcases hodd.exists_bit1 with ⟨s, hs⟩
  rw [hs] at hv2
  exact no_torsion_of_commute_square_odd hgen hcomm hv2 htinj htors

/- accepted add_to_file helper 17 -/
lemma presentedGroup_fin_two_closure_pair (rels : Set (FreeGroup (Fin 2))) :
    Subgroup.closure
      ({PresentedGroup.of (rels := rels) (0 : Fin 2),
        PresentedGroup.of (rels := rels) (1 : Fin 2)} :
        Set (PresentedGroup rels)) = ⊤ := by
  have hset :
      ({PresentedGroup.of (rels := rels) (0 : Fin 2),
        PresentedGroup.of (rels := rels) (1 : Fin 2)} :
        Set (PresentedGroup rels)) = Set.range (PresentedGroup.of (rels := rels)) := by
    ext x
    constructor
    · intro hx
      simp at hx
      rcases hx with rfl | rfl
      · exact ⟨0, rfl⟩
      · exact ⟨1, rfl⟩
    · rintro ⟨i, rfl⟩
      fin_cases i <;> simp
  rw [hset]
  exact PresentedGroup.closure_range_of rels

/- accepted add_to_file helper 18 -/
noncomputable def presentedCommEquiv {K : Type*} [Group K] (v t : K) (n : ℤ)
    (hcomm : v * t = t * v)
    (hsq : v * v = t ^ (2 * n))
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    PresentedGroup (classificationCommRels n) ≃* K := by
  let a : PresentedGroup (classificationCommRels n) := PresentedGroup.of 0
  let b : PresentedGroup (classificationCommRels n) := PresentedGroup.of 1
  have hrel1 : a * b * a⁻¹ * b⁻¹ = 1 := by
    have h := PresentedGroup.one_of_mem
      (rels := classificationCommRels n)
      (x := FreeGroup.of (0 : Fin 2) * FreeGroup.of (1 : Fin 2) *
        (FreeGroup.of (0 : Fin 2))⁻¹ * (FreeGroup.of (1 : Fin 2))⁻¹)
      (by simp [classificationCommRels])
    change a * b * a⁻¹ * b⁻¹ = 1 at h
    exact h
  have hcommP : a * b = b * a := by
    calc
      a * b = (a * b * a⁻¹ * b⁻¹) * (b * a) := by group
      _ = b * a := by rw [hrel1, one_mul]
  have hrel2 : a ^ (2 : ℕ) * (b ^ (2 * n))⁻¹ = 1 := by
    have h := PresentedGroup.one_of_mem
      (rels := classificationCommRels n)
      (x := (FreeGroup.of (0 : Fin 2)) ^ (2 : ℕ) *
        ((FreeGroup.of (1 : Fin 2)) ^ (2 * n))⁻¹)
      (by simp [classificationCommRels])
    change a ^ (2 : ℕ) * (b ^ (2 * n))⁻¹ = 1 at h
    exact h
  have hsqP : a * a = b ^ (2 * n) := by
    have h := mul_inv_eq_one.mp hrel2
    simpa [sq] using h
  have hnf := twoSidedNF_eq_univ_of_commute_square a b hcommP hsqP
    (presentedGroup_fin_two_closure_pair (classificationCommRels n))
  let φ : Fin 2 → K := fun i => if i = 0 then v else t
  have hrels : ∀ r ∈ classificationCommRels n, (FreeGroup.lift φ) r = 1 := by
    intro r hr
    simp [classificationCommRels] at hr
    rcases hr with rfl | rfl
    · simp [φ]
      calc
        v * t * v⁻¹ * t⁻¹ = (v * t) * (v⁻¹ * t⁻¹) := by group
        _ = (t * v) * (v⁻¹ * t⁻¹) := by rw [hcomm]
        _ = 1 := by group
    · simp [φ]
      calc
        v ^ 2 * (t ^ (2 * n))⁻¹ = (v * v) * (t ^ (2 * n))⁻¹ := by rw [sq]
        _ = 1 := by rw [hsq, mul_inv_cancel]
  let f : PresentedGroup (classificationCommRels n) →* K := PresentedGroup.toGroup hrels
  have fa : f a = v := by
    simp [f, a, φ, PresentedGroup.toGroup.of]
  have fb : f b = t := by
    simp [f, b, φ, PresentedGroup.toGroup.of]
  exact mulEquivOfTwoSidedNF f a b v t fa fb hnf hgen hvH htinj

/- accepted add_to_file helper 19 -/
lemma presentedCommEquiv_apply_of_zero {K : Type*} [Group K] (v t : K) (n : ℤ)
    (hcomm : v * t = t * v) (hsq : v * v = t ^ (2 * n))
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    presentedCommEquiv v t n hcomm hsq hgen hvH htinj
      (PresentedGroup.of (0 : Fin 2)) = v := by
  simp [presentedCommEquiv, mulEquivOfTwoSidedNF, PresentedGroup.toGroup.of]

lemma presentedCommEquiv_apply_of_one {K : Type*} [Group K] (v t : K) (n : ℤ)
    (hcomm : v * t = t * v) (hsq : v * v = t ^ (2 * n))
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    presentedCommEquiv v t n hcomm hsq hgen hvH htinj
      (PresentedGroup.of (1 : Fin 2)) = t := by
  simp [presentedCommEquiv, mulEquivOfTwoSidedNF, PresentedGroup.toGroup.of]

/- accepted add_to_file helper 20 -/
noncomputable def presentedInvEquiv {K : Type*} [Group K] (v t : K)
    (hconj : v * t * v⁻¹ = t⁻¹)
    (hsq : v * v = 1)
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    PresentedGroup classificationInvRels ≃* K := by
  let a : PresentedGroup classificationInvRels := PresentedGroup.of 0
  let b : PresentedGroup classificationInvRels := PresentedGroup.of 1
  have hrel1 : a * b * a⁻¹ * b = 1 := by
    have h := PresentedGroup.one_of_mem
      (rels := classificationInvRels)
      (x := FreeGroup.of (0 : Fin 2) * FreeGroup.of (1 : Fin 2) *
        (FreeGroup.of (0 : Fin 2))⁻¹ * FreeGroup.of (1 : Fin 2))
      (by simp [classificationInvRels])
    change a * b * a⁻¹ * b = 1 at h
    exact h
  have hconjP : a * b * a⁻¹ = b⁻¹ := by
    calc
      a * b * a⁻¹ = (a * b * a⁻¹ * b) * b⁻¹ := by group
      _ = b⁻¹ := by rw [hrel1, one_mul]
  have hrel2 : a ^ (2 : ℕ) = 1 := by
    have h := PresentedGroup.one_of_mem
      (rels := classificationInvRels)
      (x := (FreeGroup.of (0 : Fin 2)) ^ (2 : ℕ))
      (by simp [classificationInvRels])
    change a ^ (2 : ℕ) = 1 at h
    exact h
  have hsqP : a * a = 1 := by
    simpa [sq] using hrel2
  have hnf := twoSidedNF_eq_univ_of_inversion a b hconjP hsqP
    (presentedGroup_fin_two_closure_pair classificationInvRels)
  let φ : Fin 2 → K := fun i => if i = 0 then v else t
  have hrels : ∀ r ∈ classificationInvRels, (FreeGroup.lift φ) r = 1 := by
    intro r hr
    simp [classificationInvRels] at hr
    rcases hr with rfl | rfl
    · simp [φ]
      rw [hconj, inv_mul_cancel]
    · simp [φ]
      rw [sq, hsq]
  let f : PresentedGroup classificationInvRels →* K := PresentedGroup.toGroup hrels
  have fa : f a = v := by
    simp [f, a, φ, PresentedGroup.toGroup.of]
  have fb : f b = t := by
    simp [f, b, φ, PresentedGroup.toGroup.of]
  exact mulEquivOfTwoSidedNF f a b v t fa fb hnf hgen hvH htinj

lemma presentedInvEquiv_apply_of_zero {K : Type*} [Group K] (v t : K)
    (hconj : v * t * v⁻¹ = t⁻¹) (hsq : v * v = 1)
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    presentedInvEquiv v t hconj hsq hgen hvH htinj
      (PresentedGroup.of (0 : Fin 2)) = v := by
  simp [presentedInvEquiv, mulEquivOfTwoSidedNF, PresentedGroup.toGroup.of]

lemma presentedInvEquiv_apply_of_one {K : Type*} [Group K] (v t : K)
    (hconj : v * t * v⁻¹ = t⁻¹) (hsq : v * v = 1)
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    presentedInvEquiv v t hconj hsq hgen hvH htinj
      (PresentedGroup.of (1 : Fin 2)) = t := by
  simp [presentedInvEquiv, mulEquivOfTwoSidedNF, PresentedGroup.toGroup.of]

/- accepted add_to_file helper 21 -/
noncomputable def directProductEquivOfCommute {K : Type*} [Group K] (v t : K) (n : ℤ)
    (hcomm : v * t = t * v)
    (hv2 : v * v = t ^ (2 * n))
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    Multiplicative ℤ × Multiplicative (ZMod 2) ≃* K := by
  let u : K := v * t ^ (-n)
  have hu2 : u * u = 1 := by
    dsimp [u]
    calc
      (v * t ^ (-n)) * (v * t ^ (-n))
          = (v * (t ^ (-n) * v)) * t ^ (-n) := by group
      _ = (v * (v * t ^ (-n))) * t ^ (-n) := by
        rw [zpow_commute_left hcomm]
      _ = ((v * v) * t ^ (-n)) * t ^ (-n) := by group
      _ = 1 := by
        rw [hv2, ← zpow_add, ← zpow_add]
        have hzero : 2 * n + -n + -n = 0 := by ring
        rw [hzero]
        simp
  have hu_ne : u ≠ 1 := by
    intro hu1
    have hv_eq : v = t ^ n := by
      calc
        v = (v * t ^ (-n)) * t ^ n := by group
        _ = u * t ^ n := rfl
        _ = t ^ n := by rw [hu1, one_mul]
    have hvmem : v ∈ Subgroup.zpowers t := by
      rw [Subgroup.mem_zpowers_iff]
      exact ⟨n, hv_eq.symm⟩
    exact hvH hvmem
  have hu2pow : u ^ (2 : ℕ) = 1 := by
    rw [sq]
    exact hu2
  have hu_order : orderOf u = 2 := orderOf_eq_prime hu2pow hu_ne
  let fT : Multiplicative ℤ →* K := zpowersHom K t
  let fC : Multiplicative (ZMod 2) →* K := zmodTwoHomOfOrderTwo u hu_order
  have htu : Commute u t := by
    have hvt : Commute v t := hcomm
    have htn : Commute (t ^ (-n)) t :=
      (Commute.refl t).zpow_left (-n)
    exact hvt.mul_left htn
  have hcomm_fg : ∀ (z : Multiplicative ℤ) (c : Multiplicative (ZMod 2)),
      Commute (fT z) (fC c) := by
    intro z c
    have hz : fT z = t ^ Multiplicative.toAdd z := by
      simp [fT, zpowersHom_apply]
    have hc_mem : fC c ∈ Subgroup.zpowers u := by
      change ((zmodTwoEquivZpowers u hu_order) c : K) ∈ Subgroup.zpowers u
      exact ((zmodTwoEquivZpowers u hu_order) c).property
    rw [Subgroup.mem_zpowers_iff] at hc_mem
    rcases hc_mem with ⟨q, hq⟩
    rw [hz, ← hq]
    exact (Commute.zpow_zpow htu q (Multiplicative.toAdd z)).symm
  let F : Multiplicative ℤ × Multiplicative (ZMod 2) →* K :=
    MonoidHom.noncommCoprod fT fC hcomm_fg
  let a : Multiplicative ℤ × Multiplicative (ZMod 2) :=
    (1, Multiplicative.ofAdd (1 : ZMod 2))
  let b : Multiplicative ℤ × Multiplicative (ZMod 2) :=
    (Multiplicative.ofAdd (1 : ℤ), 1)
  have hcomm_ab : a * b = b * a := by
    ext <;> simp [a, b]
  have hsq_ab : a * a = b ^ (2 * (0 : ℤ)) := by
    ext <;> simp [a, b] <;> decide
  have hnf := twoSidedNF_eq_univ_of_commute_square a b hcomm_ab hsq_ab
    closure_pair_product_int_zmod_two
  have fa : F a = u := by
    simp [F, a, MonoidHom.noncommCoprod_apply, fT, fC,
      zmodTwoHomOfOrderTwo_apply_one, zpowersHom_apply]
  have fb : F b = t := by
    simp [F, b, MonoidHom.noncommCoprod_apply, fT, fC, zpowersHom_apply]
  have huH : u ∉ Subgroup.zpowers t := by
    intro humem
    rw [Subgroup.mem_zpowers_iff] at humem
    rcases humem with ⟨q, hq⟩
    have hv_mem : v ∈ Subgroup.zpowers t := by
      have hv_eq : v = u * t ^ n := by
        dsimp [u]
        group
      rw [hv_eq]
      exact mul_mem ⟨q, hq⟩ (zpow_mem (Subgroup.mem_zpowers t) n)
    exact hvH hv_mem
  have hgen_ut : Subgroup.closure {u, t} = ⊤ := by
    have hu_base : u ∈ Subgroup.closure {u, t} :=
      Subgroup.subset_closure (by simp)
    have ht_base : t ∈ Subgroup.closure {u, t} :=
      Subgroup.subset_closure (by simp)
    have hv_mem : v ∈ Subgroup.closure {u, t} := by
      have hv_eq : v = u * t ^ n := by
        dsimp [u]
        group
      rw [hv_eq]
      exact mul_mem hu_base (zpow_mem ht_base n)
    have hsubset : ({v, t} : Set K) ⊆ Subgroup.closure {u, t} := by
      intro x hx
      simp at hx
      rcases hx with rfl | rfl
      · exact hv_mem
      · exact ht_base
    have hle : Subgroup.closure {v, t} ≤ Subgroup.closure {u, t} :=
      (Subgroup.closure_le _).mpr hsubset
    apply top_unique
    rwa [hgen] at hle
  exact mulEquivOfTwoSidedNF F a b u t fa fb hnf hgen_ut huH htinj

/- accepted add_to_file helper 22 -/
lemma multiplicative_zmod_two_one_mul_self :
    Multiplicative.ofAdd (1 : ZMod 2) * Multiplicative.ofAdd (1 : ZMod 2) = 1 := by
  apply Multiplicative.toAdd.injective
  simp
  decide

/- accepted add_to_file helper 23 -/
abbrev ZModTwoMult : Type := Multiplicative (ZMod 2)
abbrev InfiniteDihedralModel : Type := Monoid.Coprod ZModTwoMult ZModTwoMult

/- accepted add_to_file helper 24 -/
lemma closure_infinite_dihedral_pair :
    Subgroup.closure
      ({Monoid.Coprod.inl (Multiplicative.ofAdd (1 : ZMod 2)),
        Monoid.Coprod.inl (Multiplicative.ofAdd (1 : ZMod 2)) *
          Monoid.Coprod.inr (Multiplicative.ofAdd (1 : ZMod 2))} :
        Set InfiniteDihedralModel) = ⊤ := by
  let x : InfiniteDihedralModel := Monoid.Coprod.inl (Multiplicative.ofAdd (1 : ZMod 2))
  let y : InfiniteDihedralModel := Monoid.Coprod.inr (Multiplicative.ofAdd (1 : ZMod 2))
  let b : InfiniteDihedralModel := x * y
  have hx2 : x * x = 1 := by
    calc
      x * x = Monoid.Coprod.inl
        (Multiplicative.ofAdd (1 : ZMod 2) * Multiplicative.ofAdd (1 : ZMod 2)) := by
        simp [x]
      _ = 1 := by simp [multiplicative_zmod_two_one_mul_self]
  have hy_eq : y = x * b := by
    dsimp [b]
    calc
      y = (x * x) * y := by rw [hx2, one_mul]
      _ = x * (x * y) := by group
  let S : Subgroup InfiniteDihedralModel := Subgroup.closure {x, b}
  have hxS : x ∈ S := Subgroup.subset_closure (by simp [S, x, b])
  have hbS : b ∈ S := Subgroup.subset_closure (by simp [S, x, b])
  have hyS : y ∈ S := by
    rw [hy_eq]
    exact mul_mem hxS hbS
  have hinl_le : Monoid.Coprod.inl.range ≤ S := by
    intro z hz
    rcases hz with ⟨c, rfl⟩
    have hc := mem_zpowers_multiplicative_zmod_two_one c
    rw [Subgroup.mem_zpowers_iff] at hc
    rcases hc with ⟨q, hq⟩
    rw [← hq]
    have hxpow : Monoid.Coprod.inl ((Multiplicative.ofAdd (1 : ZMod 2)) ^ q) = x ^ q := by
      simp [x]
    have hmem : x ^ q ∈ S := zpow_mem hxS q
    simpa [← hxpow] using hmem
  have hinr_le : Monoid.Coprod.inr.range ≤ S := by
    intro z hz
    rcases hz with ⟨c, rfl⟩
    have hc := mem_zpowers_multiplicative_zmod_two_one c
    rw [Subgroup.mem_zpowers_iff] at hc
    rcases hc with ⟨q, hq⟩
    rw [← hq]
    have hypow : Monoid.Coprod.inr ((Multiplicative.ofAdd (1 : ZMod 2)) ^ q) = y ^ q := by
      simp [y]
    have hmem : y ^ q ∈ S := zpow_mem hyS q
    simpa [← hypow] using hmem
  have hjoin : Monoid.Coprod.inl.range ⊔ Monoid.Coprod.inr.range ≤ S :=
    sup_le hinl_le hinr_le
  have htop_le : (⊤ : Subgroup InfiniteDihedralModel) ≤ S := by
    rw [← (Monoid.Coprod.codisjoint_range_inl_range_inr.eq_top)]
    exact hjoin
  have hS : S = ⊤ := top_unique htop_le
  simpa [S, x, b] using hS

/- accepted add_to_file helper 25 -/
noncomputable def infiniteDihedralEquivOfInversion {K : Type*} [Group K] (v t : K)
    (hconj : v * t * v⁻¹ = t⁻¹)
    (hsq : v * v = 1)
    (hgen : Subgroup.closure {v, t} = ⊤)
    (hvH : v ∉ Subgroup.zpowers t)
    (htinj : Function.Injective fun k : ℤ => t ^ k) :
    InfiniteDihedralModel ≃* K := by
  have hv_ne : v ≠ 1 := by
    intro hv1
    rw [hv1] at hvH
    exact hvH (Subgroup.one_mem _)
  have hv2pow : v ^ (2 : ℕ) = 1 := by
    rw [sq]
    exact hsq
  have hv_order : orderOf v = 2 := orderOf_eq_prime hv2pow hv_ne
  let w : K := v * t
  have hvinv : v⁻¹ = v := inv_eq_of_mul_eq_one_left hsq
  have hvtv : v * t * v = t⁻¹ := by
    simpa [hvinv] using hconj
  have hw2 : w * w = 1 := by
    dsimp [w]
    calc
      (v * t) * (v * t) = ((v * t) * v) * t := by group
      _ = 1 := by rw [hvtv, inv_mul_cancel]
  have hw_ne : w ≠ 1 := by
    intro hw1
    have ht_eq : t = v := by
      calc
        t = v⁻¹ * (v * t) := by group
        _ = v⁻¹ * w := by dsimp [w]
        _ = v⁻¹ := by rw [hw1, mul_one]
        _ = v := hvinv
    have hvmem : v ∈ Subgroup.zpowers t := by
      rw [← ht_eq]
      exact Subgroup.mem_zpowers t
    exact hvH hvmem
  have hw2pow : w ^ (2 : ℕ) = 1 := by
    rw [sq]
    exact hw2
  have hw_order : orderOf w = 2 := orderOf_eq_prime hw2pow hw_ne
  let fV : ZModTwoMult →* K := zmodTwoHomOfOrderTwo v hv_order
  let fW : ZModTwoMult →* K := zmodTwoHomOfOrderTwo w hw_order
  let F : InfiniteDihedralModel →* K := Monoid.Coprod.lift fV fW
  let a : InfiniteDihedralModel := Monoid.Coprod.inl (Multiplicative.ofAdd (1 : ZMod 2))
  let y : InfiniteDihedralModel := Monoid.Coprod.inr (Multiplicative.ofAdd (1 : ZMod 2))
  let b : InfiniteDihedralModel := a * y
  have hx2 : a * a = 1 := by
    calc
      a * a = Monoid.Coprod.inl
        (Multiplicative.ofAdd (1 : ZMod 2) * Multiplicative.ofAdd (1 : ZMod 2)) := by
        simp [a]
      _ = 1 := by simp [multiplicative_zmod_two_one_mul_self]
  have hy2 : y * y = 1 := by
    calc
      y * y = Monoid.Coprod.inr
        (Multiplicative.ofAdd (1 : ZMod 2) * Multiplicative.ofAdd (1 : ZMod 2)) := by
        simp [y]
      _ = 1 := by simp [multiplicative_zmod_two_one_mul_self]
  have hxinv : a⁻¹ = a := inv_eq_of_mul_eq_one_left hx2
  have hyinv : y⁻¹ = y := inv_eq_of_mul_eq_one_left hy2
  have hconj_ab : a * b * a⁻¹ = b⁻¹ := by
    calc
      a * b * a⁻¹ = ((a * a) * y) * a := by
        dsimp [b]
        rw [hxinv]
        group
      _ = y * a := by rw [hx2, one_mul]
      _ = b⁻¹ := by
        dsimp [b]
        rw [mul_inv_rev, hxinv, hyinv]
  have hnf := twoSidedNF_eq_univ_of_inversion a b hconj_ab hx2
    closure_infinite_dihedral_pair
  have fa : F a = v := by
    simp [F, a, fV, Monoid.Coprod.lift_comp_inl, zmodTwoHomOfOrderTwo_apply_one]
  have fy : F y = w := by
    simp [F, y, fW, Monoid.Coprod.lift_comp_inr, zmodTwoHomOfOrderTwo_apply_one]
  have fb : F b = t := by
    calc
      F b = F a * F y := by simp [b]
      _ = v * (v * t) := by rw [fa, fy]
      _ = t := by
        calc
          v * (v * t) = (v * v) * t := by group
          _ = t := by rw [hsq, one_mul]
  exact mulEquivOfTwoSidedNF F a b v t fa fb hnf hgen hvH htinj

/- verified submission -/
theorem index_two_infinite_cyclic_classification
    {K : Type*} [Group K] (v t : K)
    (hgen : Subgroup.closure {v, t} = ⊤)
    (htinf : Infinite (Subgroup.zpowers t))
    (hindex : (Subgroup.zpowers t).index = 2)
    (htors : ∃ x : K, x ≠ 1 ∧ IsOfFinOrder x) :
    (∃ n : ℤ,
      ∃ e : PresentedGroup
          ({FreeGroup.of (0 : Fin 2) * FreeGroup.of (1 : Fin 2) *
              (FreeGroup.of (0 : Fin 2))⁻¹ * (FreeGroup.of (1 : Fin 2))⁻¹,
            (FreeGroup.of (0 : Fin 2)) ^ (2 : ℕ) *
              ((FreeGroup.of (1 : Fin 2)) ^ (2 * n))⁻¹} :
            Set (FreeGroup (Fin 2))) ≃* K,
        e (PresentedGroup.of (0 : Fin 2)) = v ∧
        e (PresentedGroup.of (1 : Fin 2)) = t ∧
        Nonempty (K ≃* Multiplicative ℤ × Multiplicative (ZMod 2))) ∨
    (∃ e : PresentedGroup
          ({FreeGroup.of (0 : Fin 2) * FreeGroup.of (1 : Fin 2) *
              (FreeGroup.of (0 : Fin 2))⁻¹ * FreeGroup.of (1 : Fin 2),
            (FreeGroup.of (0 : Fin 2)) ^ (2 : ℕ)} :
            Set (FreeGroup (Fin 2))) ≃* K,
        e (PresentedGroup.of (0 : Fin 2)) = v ∧
        e (PresentedGroup.of (1 : Fin 2)) = t ∧
        Nonempty
          (K ≃* Monoid.Coprod (Multiplicative (ZMod 2))
            (Multiplicative (ZMod 2)))) := by
  have htinj : Function.Injective fun k : ℤ => t ^ k :=
    zpow_injective_of_infinite_zpowers htinf
  have hvH : v ∉ Subgroup.zpowers t :=
    not_mem_zpowers_of_closure_eq_top_index_two hgen hindex
  have hv2mem : v * v ∈ Subgroup.zpowers t :=
    sq_mem_zpowers_of_index_two (v := v) (t := t) hindex
  rw [Subgroup.mem_zpowers_iff] at hv2mem
  rcases hv2mem with ⟨r, hr⟩
  have hv2 : v * v = t ^ r := hr.symm
  have hcases := conjugation_cases_of_index_two (v := v) (t := t) hindex htinj
  rcases hcases with hcomm | hconj
  · have heven : Even r :=
      square_exponent_even_of_torsion hgen hcomm hv2 htinj htors
    rcases even_iff_exists_two_mul.mp heven with ⟨n, hn⟩
    have hv2n : v * v = t ^ (2 * n) := by
      simpa [hn] using hv2
    let e := presentedCommEquiv v t n hcomm hv2n hgen hvH htinj
    refine Or.inl ?_
    refine ⟨n, e, ?_, ?_, ?_⟩
    · exact presentedCommEquiv_apply_of_zero v t n hcomm hv2n hgen hvH htinj
    · exact presentedCommEquiv_apply_of_one v t n hcomm hv2n hgen hvH htinj
    · exact ⟨(directProductEquivOfCommute v t n hcomm hv2n hgen hvH htinj).symm⟩
  · have hvr : v * v = t ^ (-r) := by
      calc
        v * v = v * (v * v) * v⁻¹ := by group
        _ = v * t ^ r * v⁻¹ := by rw [hv2]
        _ = (v * t * v⁻¹) ^ r := by
          simpa using (conj_zpow (a := v) (b := t) (i := r)).symm
        _ = (t⁻¹) ^ r := by rw [hconj]
        _ = t ^ (-r) := by rw [inv_zpow']
    have hrneg : r = -r := by
      have htr : t ^ r = t ^ (-r) := by
        rw [← hv2, hvr]
      exact htinj htr
    have hr0 : r = 0 := by omega
    have hsq : v * v = 1 := by
      rw [hv2, hr0]
      simp
    let e := presentedInvEquiv v t hconj hsq hgen hvH htinj
    refine Or.inr ?_
    refine ⟨e, ?_, ?_, ?_⟩
    · exact presentedInvEquiv_apply_of_zero v t hconj hsq hgen hvH htinj
    · exact presentedInvEquiv_apply_of_one v t hconj hsq hgen hvH htinj
    · exact ⟨(infiniteDihedralEquivOfInversion v t hconj hsq hgen hvH htinj).symm⟩


#check_dependency_graph "index_two_infinite_cyclic_classification" against "{\"edges\":[{\"conclusion\":{\"name\":\"htinj\",\"statement\":\"Function.Injective fun k => t ^ k\"},\"graphEdgeId\":\"h_001_htinj\",\"premises\":[{\"name\":\"htinf\",\"statement\":\"Infinite ↥(Subgroup.zpowers t)\"}],\"rawEdgeId\":\"telescope_8\"},{\"conclusion\":{\"name\":\"hvH\",\"statement\":\"v ∉ Subgroup.zpowers t\"},\"graphEdgeId\":\"h_002_hvh\",\"premises\":[{\"name\":\"hgen\",\"statement\":\"Subgroup.closure {v, t} = ⊤\"},{\"name\":\"hindex\",\"statement\":\"(Subgroup.zpowers t).index = 2\"}],\"rawEdgeId\":\"telescope_9\"},{\"conclusion\":{\"name\":\"hv2mem\",\"statement\":\"v * v ∈ Subgroup.zpowers t\"},\"graphEdgeId\":\"h_003_hv2mem\",\"premises\":[{\"name\":\"hindex\",\"statement\":\"(Subgroup.zpowers t).index = 2\"}],\"rawEdgeId\":\"telescope_10\"},{\"conclusion\":{\"name\":\"goal\",\"statement\":\"(∃ n e, e (PresentedGroup.of 0) = v ∧ e (PresentedGroup.of 1) = t ∧ Nonempty (K ≃* Multiplicative ℤ × Multiplicative (ZMod 2))) ∨ ∃ e, e (PresentedGroup.of 0) = v ∧ e (PresentedGroup.of 1) = t ∧ Nonempty (K ≃* Monoid.Coprod (Multiplicative (ZMod 2)) (Multiplicative (ZMod 2)))\"},\"graphEdgeId\":\"h_goal\",\"premises\":[{\"name\":\"hgen\",\"statement\":\"Subgroup.closure {v, t} = ⊤\"},{\"name\":\"hindex\",\"statement\":\"(Subgroup.zpowers t).index = 2\"},{\"name\":\"htors\",\"statement\":\"∃ x, x ≠ 1 ∧ IsOfFinOrder x\"},{\"name\":\"htinj\",\"statement\":\"Function.Injective fun k => t ^ k\"},{\"name\":\"hvH\",\"statement\":\"v ∉ Subgroup.zpowers t\"},{\"name\":\"hv2mem\",\"statement\":\"v * v ∈ Subgroup.zpowers t\"}],\"rawEdgeId\":\"goal_edge\"}],\"graphId\":\"p1552_index_two_infinite_cyclic_classification\",\"reconstructedProofSha256\":\"ca16ec0b4eb68fc59e6e018796ea3e9ad62d3dfff9476d84e70f557d46735815\",\"selectedEdgeCount\":4,\"theoremName\":\"index_two_infinite_cyclic_classification\",\"topologySha256\":\"b970c05a80a45b5cb42281387b00efc48d0120f20aec20b1b700ceda483f090b\"}"
